create table if not exists public.game_reports (
  id bigint generated by default as identity primary key,
  report_type text not null,
  game_id bigint not null,
  game_name text not null,
  description text not null,
  reporter_user_id uuid references auth.users(id) on delete set null,
  reporter_email text,
  reporter_username text,
  reporter_ip text,
  has_account boolean not null default false,
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.game_reports add column if not exists reporter_username text;
alter table public.game_reports add column if not exists reporter_ip text;

create index if not exists game_reports_created_at_idx on public.game_reports (created_at desc);
create index if not exists game_reports_game_id_idx on public.game_reports (game_id);

alter table public.game_reports disable row level security;
